apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu
  name: ubuntu-node1
spec:
  tolerations:
  - key: key
    operator: Equal
    value: node1
    effect: NoSchedule
  containers:
  - name: ubuntu
    image: ubuntu:latest
